services:
  - type: web
    name: reading-book-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_NAME
        value: ReadingBook
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 9000
      - key: API_VERSION
        value: v1
      - key: API_PREFIX
        value: /api
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: combined
      - key: RATE_LIMIT
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: "GET,HEAD,PUT,PATCH,POST,DELETE"
      - key: CORS_CREDENTIALS
        value: "true"
      - key: OTP_LENGTH
        value: 6
      - key: OTP_EXPIRY
        value: 300
      - key: OTP_PROVIDER
        value: email
      - key: CACHE_TTL
        value: 300
      - key: CACHE_CHECKPERIOD
        value: 120
      - key: UPLOAD_LIMIT
        value: 10mb
      - key: ALLOWED_FORMATS
        value: "jpg,jpeg,png,gif,pdf"
      - key: STORAGE_PATH
        value: uploads
    # Add your environment variables here:
    # - key: FIREBASE_PROJECT_ID
    #   sync: false
    # - key: FIREBASE_DATABASE_URL
    #   sync: false
    # - key: FIREBASE_PRIVATE_KEY_ID
    #   sync: false
    # - key: FIREBASE_PRIVATE_KEY
    #   sync: false
    # - key: FIREBASE_CLIENT_EMAIL
    #   sync: false
    # - key: FIREBASE_CLIENT_ID
    #   sync: false
    # - key: RESEND_API_KEY
    #   sync: false
    # - key: EMAIL_FROM
    #   sync: false
    # - key: JWT_SECRET
    #   sync: false
    # - key: JWT_EXPIRY
    #   sync: false
