services:
  - type: web
    name: reading-book-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node build/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_NAME
        value: ReadingBook
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 9000
      - key: API_VERSION
        value: v1
      - key: API_PREFIX
        value: /api
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: combined
      - key: RATE_LIMIT
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: "GET,HEAD,PUT,PATCH,POST,DELETE"
      - key: CORS_CREDENTIALS
        value: "true"
      - key: OTP_LENGTH
        value: 6
      - key: OTP_EXPIRY
        value: 300
      - key: OTP_PROVIDER
        value: email
      - key: CACHE_TTL
        value: 300
      - key: CACHE_CHECKPERIOD
        value: 120
      - key: UPLOAD_LIMIT
        value: 10mb
      - key: ALLOWED_FORMATS
        value: "jpg,jpeg,png,gif,pdf"
      - key: STORAGE_PATH
        value: uploads
    # Firebase Configuration (REQUIRED - Add your actual values)
    - key: FIREBASE_PROJECT_ID
      sync: false
    - key: FIREBASE_PROJECT_NUMBER
      sync: false
    - key: FIREBASE_DATABASE_URL
      sync: false
    - key: FIREBASE_WEB_API_KEY
      sync: false
    - key: FIREBASE_PRIVATE_KEY_ID
      sync: false
    - key: FIREBASE_PRIVATE_KEY
      sync: false
    - key: FIREBASE_CLIENT_EMAIL
      sync: false
    - key: FIREBASE_CLIENT_ID
      sync: false

    # Email Configuration (REQUIRED - Add your actual values)
    - key: SMTP_HOST
      value: smtp.gmail.com
    - key: SMTP_PORT
      value: 587
    - key: SMTP_USERNAME
      sync: false
    - key: SMTP_PASSWORD
      sync: false
    - key: EMAIL_FROM
      sync: false
    - key: EMAIL_PROVIDER
      value: smtp
    - key: SENDGRID_API_KEY
      sync: false

    # JWT Configuration (REQUIRED - Add your actual values)
    - key: JWT_SECRET
      sync: false
    - key: JWT_EXPIRY
      value: 1h
